fix: editorconfig and precommit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,10 @@
 . "$(dirname "$0")/_/husky.sh"
 
 npx pretty-quick --staged && npm run lint
+
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "develop" -o "$branch" = "master" ]; then
+  echo "You can't commit directly to this branch"
+  exit 1
+fi
