fix: editorconfig and precommit (#27)
* fix: editorconfig and precommit

* feat: Comment for preventing commit to master and develop branch

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,11 @@
 . "$(dirname "$0")/_/husky.sh"
 
 npx pretty-quick --staged && npm run lint
+
+# Prevent direct commit to master and develop branch
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "develop" -o "$branch" = "master" ]; then
+  echo "You can't commit directly to this branch"
+  exit 1
+fi
